name: "Release & Publish"
on:
  push:
    tags:
      - 'v*'

jobs:
  # Run all tests defined in the test workflow before proceeding with deployment
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yaml

  # Only deploy after tests have passed successfully
  deploy:
    name: Deploy & Publish
    needs: test
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "false"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
